# -*- coding: utf-8 -*-
"""smell_count.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggVMuvn1WJRRwvKxEKf56B-VedniBVT_
"""

!rm -rf content/ml_smells_detector/

!unzip -q '/content/results_code_qwen1.5-agent.zip'

import pandas as pd
import os
import re
from pathlib import Path


ROOT = '/content/content/ml_smells_detector/smell_results/detector_outputs'
TOTAL_FILES = 82


canonical_smells = {
    "Pandas": [
        ("Unnecessary Iteration", ["iterrows", "unnecessary iter"]),
        ("DataFrame Iteration Modification", ["iteration modification"]),
        ("Chain Indexing", ["chain index"]),
        ("Datatype Checker", ["datatype", "data type", "dtype"]),
        ("Column Selection Checker", ["column selection"]),
        ("Merge Parameter Checker", ["merge parameter", "merge"]),
        ("InPlace Checker", ["inplace"]),
        ("DataFrame Conversion Checker", ["conversion", r"\.values", "to_numpy"]),
    ],
    "NumPy": [
        ("NaN Equality Checker", ["nan equality", "nan comparison", "isnan"]),
        ("Randomness Control Checker", ["random seed", "randomness", "random state"]),
    ],
    "TensorFlow": [
        ("Early Stopping Checker", ["early stopping"]),
        ("Checkpointing Checker", ["checkpoint"]),
        ("Memory Release Checker", ["memory release", "memory management"]),
        ("Tensor Array Checker", ["tensor array", "tensorarray"]),
        ("Dependent Threshold Checker", ["threshold", "accuracy metric", "single metric"]),
        ("Logging Checker", ["logging", "tensorboard", "visualization"]),
        ("Dropout Usage Checker", ["dropout"]),
        ("Data Augmentation Checker", ["augmentation"]),
    ],
    "PyTorch": [
        ("Deterministic Algorithm Usage Checker", ["deterministic"]),
        ("Model Evaluation Checker", ["model eval", "evaluation"]),
        ("Dropout Usage Checker", ["dropout"]),
    ],
    "Hugging Face": [
        ("Early Stopping", ["early stopping"]),
    ],
    "General ML": [
        ("Data Leakage", ["data leakage", "leakage"]),
        ("Magic Numbers", ["magic number", "hard.?coded constant"]),
        ("Cross Validation", ["cross.?valid"]),
        ("Imbalanced Dataset Handling", ["imbalanced", "class imbalance"]),
        ("Metric Selection", ["metric", "accuracy metric", "single metric", "overreliance"]),
        ("Model Persistence", ["model persist", "model sav", "save model"]),
        ("Reproducibility", ["reproducib", "random seed"]),
        ("Data Loading", ["data load", "inefficient load"]),
        ("Error Handling", ["error handling", "exception", "try.?except"]),
        ("Hardcoded Filepaths", ["hardcoded file", "hardcoded path", "file path"]),
        ("Documentation", ["documentation", "docstring", "comment"]),
    ],
}

def match_smell(framework, smell_str):
    smell_lower = str(smell_str).lower()
    for fw in [framework, None]:
        entries = canonical_smells.get(fw, []) if fw else [e for v in canonical_smells.values() for e in v]
        for canonical_name, keywords in entries:
            for kw in keywords:
                if re.search(kw, smell_lower):
                    return canonical_name
    return smell_str

def get_status(row):
    i, f = row['Initial_Count'], row['Final_Count']
    if i > 0 and f == 0:
        return 'Fixed'
    elif i == 0 and f > 0:
        return 'Newly Introduced'
    elif i > 0 and f > 0 and f < i:
        return 'Partially Fixed'
    elif i > 0 and f >= i:
        return 'Not Fixed'
    return 'No Change'

def load_round_csv(dirpath, filename, framework_col='Framework', smell_col='Smell/Checker Name'):
    """Load a round CSV and return grouped (Framework, Smell, Project_File) -> Count."""
    df = pd.read_csv(os.path.join(dirpath, filename))
    df['Project_File'] = df['File'] if 'File' in df.columns else Path(dirpath).name
    df['Smell'] = df.apply(lambda r: match_smell(r[framework_col], r[smell_col]), axis=1)
    g = df.groupby(['Framework', 'Smell', 'Project_File'])['Count'].sum().reset_index()
    g.columns = ['Framework', 'Smell', 'Project_File', 'Count']
    return g

records = []
rounds_to_fix_records = []
for dirpath, dirnames, filenames in os.walk(ROOT):
    init_file  = next((f for f in filenames if 'initial_analysis_report' in f and f.endswith('.csv')), None)
    final_file = next((f for f in filenames if 'final_fixed_analysis_report' in f and f.endswith('.csv')), None)
    if not (init_file and final_file):
        continue

    project = Path(dirpath).name

    round_files = sorted(
        [f for f in filenames if re.match(r'fixed_round_\d+_analysis_report\.csv', f)],
        key=lambda x: int(re.search(r'fixed_round_(\d+)', x).group(1))
    )
    max_rounds = len(round_files)

    try:
        init_g  = load_round_csv(dirpath, init_file)
        final_g = load_round_csv(dirpath, final_file)
    except Exception as e:
        print(f"Skipping {project}: {e}")
        continue

    init_g.columns  = ['Framework', 'Smell', 'Project_File', 'Initial_Count']
    final_g.columns = ['Framework', 'Smell', 'Project_File', 'Final_Count']

    m = pd.merge(init_g, final_g, on=['Framework', 'Smell', 'Project_File'], how='outer').fillna(0)
    m['Initial_Count'] = m['Initial_Count'].astype(int)
    m['Final_Count']   = m['Final_Count'].astype(int)
    m['Status']        = m.apply(get_status, axis=1)
    m.insert(0, 'Project', project)
    records.append(m)

    if not round_files:
        continue

    round_dfs = {}
    for rf in round_files:
        rnum = int(re.search(r'fixed_round_(\d+)', rf).group(1))
        try:
            rg = load_round_csv(dirpath, rf)
            rg.columns = ['Framework', 'Smell', 'Project_File', f'Round_{rnum}']
            round_dfs[rnum] = rg
        except Exception as e:
            print(f"  Skipping round file {rf} in {project}: {e}")

    initially_present = init_g[init_g['Initial_Count'] > 0][['Framework', 'Smell', 'Project_File']].copy()

    if initially_present.empty or not round_dfs:
        continue

    merged = initially_present.copy()
    for rnum in sorted(round_dfs.keys()):
        merged = pd.merge(merged, round_dfs[rnum], on=['Framework', 'Smell', 'Project_File'], how='left')

    round_cols = [f'Round_{r}' for r in sorted(round_dfs.keys())]
    merged[round_cols] = merged[round_cols].fillna(0).astype(int)

    def first_zero_round(row):
        for r in sorted(round_dfs.keys()):
            col = f'Round_{r}'
            if col in row and row[col] == 0:
                return r
        return None
    merged['First_Zero_Round'] = merged.apply(first_zero_round, axis=1)
    merged.insert(0, 'Project', project)
    merged['Max_Rounds_Available'] = max_rounds
    rounds_to_fix_records.append(merged)

if not records:
    print("No valid CSVs found. Exiting.")
    exit()

all_data = pd.concat(records, ignore_index=True)

summary_rows = []
for framework, entries in canonical_smells.items():
    for canonical_name, _ in entries:
        subset = all_data[(all_data['Framework'] == framework) & (all_data['Smell'] == canonical_name)]
        files_introduced = subset.loc[subset['Initial_Count'] > 0, 'Project_File'].nunique()
        files_fixed      = subset.loc[subset['Status'] == 'Fixed', 'Project_File'].nunique()
        summary_rows.append({
            'Framework':                 framework,
            'Smell':                     canonical_name,
            'No_of_Files_Introduced_In': files_introduced,
            'Introduced_%':              round(files_introduced / TOTAL_FILES * 100, 2),
            'No_of_Files_Fixed_In':      files_fixed,
            'Fixed_%':                   round(files_fixed / files_introduced * 100, 2) if files_introduced > 0 else 0.0,
        })

smell_summary_df = pd.DataFrame(summary_rows)

avg_rounds_df = pd.DataFrame()

if rounds_to_fix_records:
    all_rounds = pd.concat(rounds_to_fix_records, ignore_index=True)

    fixed_mask = all_rounds['First_Zero_Round'].notna()

    avg_rounds = (
        all_rounds[fixed_mask]
        .groupby(['Framework', 'Smell'])['First_Zero_Round']
        .agg(
            Avg_Rounds_To_Fix='mean',
            Min_Rounds_To_Fix='min',
            Max_Rounds_To_Fix='max',
            Times_Fixed='count'
        )
        .round(2)
        .reset_index()
    )

    never_fixed = (
        all_rounds[~fixed_mask]
        .groupby(['Framework', 'Smell'])
        .size()
        .reset_index(name='Times_Never_Fixed')
    )

    avg_rounds_df = pd.merge(avg_rounds, never_fixed, on=['Framework', 'Smell'], how='outer').fillna(0)
    avg_rounds_df['Times_Never_Fixed'] = avg_rounds_df['Times_Never_Fixed'].astype(int)

    smell_summary_df = pd.merge(
        smell_summary_df,
        avg_rounds_df[['Framework', 'Smell', 'Avg_Rounds_To_Fix', 'Min_Rounds_To_Fix', 'Max_Rounds_To_Fix', 'Times_Never_Fixed']],
        on=['Framework', 'Smell'],
        how='left'
    )

smell_summary_df.to_csv('smell_introduced_vs_fixed.csv', index=False)

framework_summary_rows = []
for framework in all_data['Framework'].unique():
    subset = all_data[all_data['Framework'] == framework]
    files_introduced = subset.loc[subset['Initial_Count'] > 0, 'Project_File'].nunique()
    files_fixed      = subset.loc[subset['Status'] == 'Fixed', 'Project_File'].nunique()
    fixed_pct        = round(files_fixed / files_introduced * 100, 2) if files_introduced > 0 else 0.0

    fw_round_stats = {'Avg_Rounds_To_Fix': None, 'Min_Rounds_To_Fix': None, 'Max_Rounds_To_Fix': None, 'Times_Never_Fixed': 0}
    if not avg_rounds_df.empty:
        fw_rows = avg_rounds_df[avg_rounds_df['Framework'] == framework]
        if not fw_rows.empty:
            fixed_fw = fw_rows[fw_rows['Times_Fixed'] > 0]
            if not fixed_fw.empty:
                total_fixed = fixed_fw['Times_Fixed'].sum()
                weighted_avg = (fixed_fw['Avg_Rounds_To_Fix'] * fixed_fw['Times_Fixed']).sum() / total_fixed
                fw_round_stats['Avg_Rounds_To_Fix'] = round(weighted_avg, 2)
                fw_round_stats['Min_Rounds_To_Fix'] = int(fixed_fw['Min_Rounds_To_Fix'].min())
                fw_round_stats['Max_Rounds_To_Fix'] = int(fixed_fw['Max_Rounds_To_Fix'].max())
            fw_round_stats['Times_Never_Fixed'] = int(fw_rows['Times_Never_Fixed'].sum())

    framework_summary_rows.append({
        'Framework':                    framework,
        'Files_With_Smells_Introduced': files_introduced,
        'Files_With_Smells_Fixed':      files_fixed,
        'Fixed_%':                      fixed_pct,
        'Avg_Rounds_To_Fix':            fw_round_stats['Avg_Rounds_To_Fix'],
        'Min_Rounds_To_Fix':            fw_round_stats['Min_Rounds_To_Fix'],
        'Max_Rounds_To_Fix':            fw_round_stats['Max_Rounds_To_Fix'],
        'Times_Never_Fixed':            fw_round_stats['Times_Never_Fixed'],
    })

framework_summary_df = pd.DataFrame(framework_summary_rows)
framework_summary_df.to_csv('framework_summary_introduced_fixed_with_pct.csv', index=False)

if rounds_to_fix_records:
    all_rounds.to_csv('per_file_rounds_to_fix.csv', index=False)

print("Done! Outputs:")
print("  smell_introduced_vs_fixed.csv          — per smell: introduced, fixed %, avg/min/max rounds to fix")
print("  framework_summary_introduced_fixed_with_pct.csv — per framework summary")
print("  per_file_rounds_to_fix.csv             — per file × smell: which round it was fixed")