# -*- coding: utf-8 -*-
"""smell-count.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Og74Hss47Ye28WKfjAUnNyBlqjuOZEoX
"""



!git clone https://github.com/KarthikShivasankar/ml_smells_detector.git

# Commented out IPython magic to ensure Python compatibility.
# %cd ml_smells_detector/

!pip install -e .

!unzip -q '/content/qwen-3b.zip'

!rm -r '/content/ml_smells_detector/smell_results'



import subprocess
import re
import csv
import shutil
from pathlib import Path

BASE_DIR = Path("/content/ml_smells_detector/runs")
RESULTS_DIR = Path("smell_results")
RESULTS_DIR.mkdir(exist_ok=True)



def extract_python_blocks(text: str):
    """
    Extract all code blocks — tries ```python first, then any ``` block.
    Returns list of code strings.
    """
    blocks = re.findall(r"```[ \t]*[Pp]ython[ \t]*\n(.*?)```", text, re.DOTALL)
    if blocks:
        return blocks

    blocks = re.findall(r"```[ \t]*(?:\w+)?[ \t]*\n(.*?)```", text, re.DOTALL)
    return blocks


def get_combined_code(raw_text: str):
    """
    1. Try to extract fenced blocks — if found and parsable, use them.
    2. If no blocks found, or blocks not parsable, try the raw file as-is.
    3. If raw is parsable, use it directly (no extraction).
    4. Otherwise return (None, reason).
    Returns (code: str | None, reason: str | None)
    """
    blocks = extract_python_blocks(raw_text)

    if blocks:
        combined = "\n\n".join(blocks)
        try:
            compile(combined, "<string>", "exec")
            return combined, None
        except SyntaxError as block_err:

            pass
    else:
        block_err = None


    try:
        compile(raw_text, "<string>", "exec")
        return raw_text, None
    except SyntaxError as raw_err:
        if blocks:
            return None, f"Blocks found but not parsable; raw file also not parsable: {raw_err}"
        return None, f"No python blocks found and raw file not parsable: {raw_err}"


def count_sloc(code: str) -> int:
    try:
        from radon.raw import analyze
        result = analyze(code)
        return max(result.sloc, 1)
    except Exception:
        lines = code.splitlines()
        sloc = sum(
            1 for line in lines
            if line.strip() and not line.strip().startswith("#")
        )
        return max(sloc, 1)


def compute_density(smell_count: int, sloc: int) -> float:
    return round((smell_count / sloc) * 100, 4) if sloc > 0 else 0.0


def clear_previous_report(output_dir: Path):
    for report in output_dir.rglob("analysis_report.csv"):
        report.unlink()
        print(f"  [cleared] {report}")


def run_smell_detector(target_file: Path):
    try:
        result = subprocess.run(
            ["ml_smell_detector", "analyze", str(target_file)],
            cwd=str(target_file.parent),
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            return False, result.stderr
        return True, result.stdout
    except Exception as e:
        return False, str(e)


def count_smells_from_csv(output_dir: Path):
    """
    Returns (total_count: int, found: bool, report_path: Path | None)
    """
    report = output_dir / "analysis_report.csv"
    if not report.exists():
        matches = list(output_dir.rglob("analysis_report.csv"))
        if not matches:
            return 0, False, None
        report = matches[0]
    try:
        with open(report, newline="", encoding="utf-8", errors="replace") as f:
            reader = csv.reader(f)
            rows = list(reader)
        count = max(0, len(rows) - 1)
        return count, True, report
    except Exception as e:
        print(f"  [csv read error] {report}: {e}")
        return 0, False, None


def save_detector_output(source_report: Path, competition_name: str, file_stem: str):
    """
    Copy analysis_report.csv into:
    RESULTS_DIR/detector_outputs/<competition>/<file_stem>_analysis_report.csv
    """
    if source_report is None or not source_report.exists():
        return
    dest_dir = RESULTS_DIR / "detector_outputs" / competition_name
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / f"{file_stem}_analysis_report.csv"
    shutil.copy2(str(source_report), str(dest))
    print(f"  [saved report] {dest}")



summary_rows = []
errors = []
total_files = 0
parse_failures = 0

for competition_folder in BASE_DIR.iterdir():

    if not competition_folder.is_dir():
        continue

    print(f"\nProcessing: {competition_folder.name}")

    file_stats = {}

    target_files = []

    initial = competition_folder / "initial.py"
    if initial.exists():
        target_files.append(initial)

    final_fixed = competition_folder / "final_fixed.py"
    if final_fixed.exists():
        target_files.append(final_fixed)

    fixed_rounds = list(competition_folder.glob("fixed_round*.py"))
    target_files.extend(fixed_rounds)

    for file in target_files:
        total_files += 1
        print(f"  Extracting from {file.name}")

        try:
            raw_text = file.read_text(encoding="utf-8", errors="replace")
        except Exception as e:
            errors.append(f"{file}: Read failed -> {e}")
            parse_failures += 1
            continue

        combined_code, reason = get_combined_code(raw_text)

        if combined_code is None:
            errors.append(f"{file}: {reason}")
            parse_failures += 1
            continue

        sloc = count_sloc(combined_code)

        temp_file = competition_folder / f"__temp_{file.stem}.py"
        try:
            temp_file.write_text(combined_code, encoding="utf-8")
        except Exception as e:
            errors.append(f"{file}: Temp file write failed -> {e}")
            parse_failures += 1
            continue


        clear_previous_report(competition_folder)

        print(f"  Analyzing extracted code from {file.name}")

        success, message = run_smell_detector(temp_file)

        if not success:
            errors.append(f"{file}: {message}")
            temp_file.unlink(missing_ok=True)
            continue

        generated_output = competition_folder

        if not (generated_output / "analysis_report.csv").exists():
            if not list(generated_output.rglob("analysis_report.csv")):
                errors.append(f"{file}: No analysis_report.csv found in {generated_output}")
                temp_file.unlink(missing_ok=True)
                continue

        smell_count, csv_found, report_path = count_smells_from_csv(generated_output)
        if not csv_found:
            print(f"  [warn] no analysis_report.csv in {generated_output}")

        density = compute_density(smell_count, sloc)


        save_detector_output(report_path, competition_folder.name, file.stem)

        file_stats[file.stem] = {
            "smell_count":   smell_count,
            "sloc":          sloc,
            "smell_density": density,
        }

        print(f"  {file.name}: smell_count={smell_count}  sloc={sloc}  density={density}")

        temp_file.unlink(missing_ok=True)

    row = {"competition": competition_folder.name}
    for stem, stats in file_stats.items():
        row[f"{stem}_smell_count"]   = stats["smell_count"]
        row[f"{stem}_sloc"]          = stats["sloc"]
        row[f"{stem}_smell_density"] = stats["smell_density"]

    summary_rows.append(row)




if summary_rows:
    columns = set()
    for row in summary_rows:
        columns.update(row.keys())

    columns.discard("competition")
    columns = ["competition"] + sorted(columns)

    density_cols = [c for c in columns if c.endswith("_smell_density")]
    avg_row = {"competition": "AVERAGE"}
    for col in density_cols:
        values = [r[col] for r in summary_rows if col in r and r[col] != ""]
        avg_row[col] = round(sum(values) / len(values), 4) if values else ""

    per_comp_avgs = []
    for row in summary_rows:
        vals = [row[c] for c in density_cols if c in row and row[c] != ""]
        if vals:
            per_comp_avgs.append(sum(vals) / len(vals))
    overall_avg = round(sum(per_comp_avgs) / len(per_comp_avgs), 4) if per_comp_avgs else ""
    print(f"\nOverall average density across all files and competitions: {overall_avg}")

    csv_path = RESULTS_DIR / "summary.csv"

    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=columns, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(summary_rows)
        writer.writerow({})
        writer.writerow(avg_row)

    print(f"Wrote: {csv_path}")



if errors:
    error_file = RESULTS_DIR / "errors.txt"
    error_file.write_text("\n".join(errors))
    print(f"Wrote: {error_file} ({len(errors)} errors)")



print(f"\nSummary:")
print(f"  Total files attempted : {total_files}")
print(f"  Parse/read failures   : {parse_failures}")
print(f"  Successfully analysed : {total_files - parse_failures}")

print("\nAll competitions processed successfully.")

from google.colab import drive
drive.mount('/content/drive')

!zip -r "results_qwen_3-3.zip" "/content/ml_smells_detector/smell_results"

from google.colab import files
files.download("results_qwen_3-3.zip")